<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-02-28 06:52
=======
# Generated by Django 3.1.2 on 2021-03-07 15:10
>>>>>>> 61962f376e9d0c8880e99283078671bb43876d10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('product', '0002_auto_20210228_0652'),
=======
        ('product', '0001_initial'),
>>>>>>> 61962f376e9d0c8880e99283078671bb43876d10
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('verify_status', models.BooleanField()),
=======
>>>>>>> 61962f376e9d0c8880e99283078671bb43876d10
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='banner/static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
<<<<<<< HEAD
=======
                ('replys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
>>>>>>> 61962f376e9d0c8880e99283078671bb43876d10
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
